import * as consts from '@/api/consts';

export default {
  CURRENT_SKIN: consts.CURRENT_SKIN,
  SHOW_SONGLIST: consts.SHOW_SONGLIST,
  SHOW_MINIAUDIO: consts.SHOW_MINIAUDIO,
  LOVE_SONGS: consts.LOVE_SONGS,
  SONG_LIST_DATA: consts.SONG_LIST_DATA,
  CURRENT_SONG: consts.CURRENT_SONG,
  SHOW_GRAPH: consts.SHOW_GRAPH,
  IS_PLAYING: consts.IS_PLAYING,
  SONG_CURRENT_TIME: consts.SONG_CURRENT_TIME,
  HISTORY_SONG_DATA: consts.HISTORY_SONG_DATA,
  IS_CHANGE_AUDIO: consts.IS_CHANGE_AUDIO,
  IS_ENDED: consts.IS_ENDED,
  IS_NEXT_SONG: consts.IS_NEXT_SONG
};
